version: "3.7"
services:
  rest_api:
    restart: always
    build: "./backend/rest-api/"
    container_name: stone-rest-api-service
    command: /bin/sh -c 'sudo gunicorn -b 0.0.0.0:8082 service.start:app'
    volumes:
      - ./backend/rest-api/:/code/app/
    ports:
      - 8082:8082
    env_file:
      - ./backend/rest-api/service/.env
    depends_on:
      - database
    links:
      - database:database

  database:
    build: "./backend/database/"
    ports:
      - '3306:3306'
    container_name: stone-database-container
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
       MYSQL_DATABASE: 'logistic'
       MYSQL_USER: 'stone'
       MYSQL_PASSWORD: '77991717025'
       MYSQL_ROOT_PASSWORD: '77991717025'
    volumes:
      - ./backend/database/data:/var/lib/mysql
    restart: always