version: "3.7"
services:
  stone_logistic_rest_api:
    build: "./backend/rest-api/"
    restart: always
    container_name: stone-logistic-rest-api-service
    volumes:
      - ./backend/rest-api/:/code/app/
    expose:
      - 5000

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - stone_logistic_rest_api